name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight
  workflow_dispatch:     # allows manual trigger

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure Git Identity
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"

    - name: Fetch TryHackMe Badge
      uses: DhanushNehru/tryhackme-badge-action-workflow@v1.0
      with:
        image_path: './assets/tryhackme-badge.png'
        username: 'ronnie.jehu'      # your THM username
        user_id: '1995656'           # your THM user ID
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
