name: Update profile README
on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:
jobs:
  update_profile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Spotify CLI action
        uses: DeadPackets/spotify-now-playing-readme@v1.0
        with:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet || (git add README.md && git commit -m "🟢 Update Spotify section" && git push)
