name: Update profile README
on:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours
  workflow_dispatch:

jobs:
  update_profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp
        run: |
          timestamp=$(date -u '+%A, %B %d %Y, %H:%M UTC')
          sed -i "s|<!--TIMESTAMP-->|$timestamp|" README.md

      - name: Commit and push if changed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet || (git add README.md && git commit -m "🟢 Auto update timestamp" && git push)
          