name: Update README timestamp
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README timestamp
        run: |
          TIMESTAMP=$(date -u "+%A, %B %d, %Y at %H:%M UTC")
          sed -i "s|<!--TIMESTAMP-->.*|<!--TIMESTAMP-->${TIMESTAMP}|g" README.md

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff --quiet || (git add README.md && git commit -m "🔄 README updated: ${TIMESTAMP}" && git push)
